name: petforpat
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Existing dependencies
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.1.0

  # New dependencies
  # State Management
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.7

  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

  # Network & API
  dio: ^5.7.0
  connectivity_plus: ^6.1.1
  internet_connection_checker: ^1.0.0+1
  pretty_dio_logger: ^1.4.0

  # Dependency Injection
  get_it: ^8.0.3

  # Functional Programming
  dartz: ^0.10.1  # Fixed version here

  # Navigation
  go_router: ^12.1.1

  # UI Components
  cached_network_image: ^3.3.0
  image_picker: ^1.1.2
  multi_select_flutter: ^4.1.3

  # Utilities
  shared_preferences: ^2.3.4
  uuid: ^4.5.1
  permission_handler: ^11.3.1
  path_provider: ^2.1.5
  json_annotation: ^4.9.0

  # Chat functionality
  socket_io_client: ^2.0.3+1

  # Utilities
  intl: ^0.18.1

  # JSON Serialization
  json_serializable: ^6.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Existing dev dependencies
  flutter_lints: ^5.0.0

  # New dev dependencies
  # Code Generation
  build_runner: ^2.4.14

  # Testing
  bloc_test: ^9.1.4
  mocktail: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/robotoextrabold.ttf

    - family: Robotoo
      fonts:
        - asset: assets/fonts/robotosemibold.ttf

    - family: OpenSans
      fonts:
        - asset: assets/fonts/opensansmedium.ttf

