// Mocks generated by Mockito 5.4.5 from annotations
// in petforpat/test/bloc/adoption_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:petforpat/features/adoption/domain/entities/adoption_request.dart'
    as _i5;
import 'package:petforpat/features/adoption/domain/repositories/adoption_repository.dart'
    as _i2;
import 'package:petforpat/features/adoption/domain/usecases/submit_adoption_request.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAdoptionRepository_0 extends _i1.SmartFake
    implements _i2.AdoptionRepository {
  _FakeAdoptionRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SubmitAdoptionRequestUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubmitAdoptionRequestUseCase extends _i1.Mock
    implements _i3.SubmitAdoptionRequestUseCase {
  MockSubmitAdoptionRequestUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AdoptionRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAdoptionRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.AdoptionRepository);

  @override
  _i4.Future<void> call(_i5.AdoptionRequest? request) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [request],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
