import 'package:flutter/material.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:petforpat/app/app.dart';
import 'package:petforpat/app/service_locator/service_locator.dart';
import 'package:petforpat/features/auth/data/models/user_model.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Hive and register your model adapter
  await Hive.initFlutter();
  Hive.registerAdapter(UserModelAdapter()); // This must be generated by build_runner

  // Open the Hive box for users
  await Hive.openBox<UserModel>('users');

  // Set up dependency injection
  await setupServiceLocator();

  runApp(const PetForPatApp());
}
